# Generated by Django 2.2.7 on 2020-03-23 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('sender_name', models.CharField(blank=True, max_length=70)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('access_token', models.CharField(blank=True, max_length=250)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'mail_account',
                'unique_together': {('email',)},
            },
        ),
        migrations.CreateModel(
            name='MailUserCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.FileField(blank=True, null=True, upload_to='')),
                ('credential_detail', models.TextField(blank=True, null=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('client_secret', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's credential",
                'verbose_name_plural': "User's credentials",
                'db_table': 'mail_user_credential',
            },
        ),
        migrations.CreateModel(
            name='MailAccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.MailAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assigned Email',
                'verbose_name_plural': 'Assigned Emails',
                'db_table': 'mail_account_user',
                'unique_together': {('mail_account',)},
            },
        ),
    ]
