# Generated by Django 2.2.7 on 2020-04-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customermaildata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaildata',
            name='data_num',
            field=models.IntegerField(default=0),
        ),
    ]
